name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *" # every day at 12:00 AM UTC
  workflow_dispatch: # lets you manually trigger it too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Make daily commit
      run: |
        date > update.txt
        git config --global user.email "bot@example.com"
        git config --global user.name "Daily Commit Bot"
        git add update.txt
        git commit -m "📅 Daily commit: $(date)"
        git push
