name: Daily Commit

on:
  schedule:
    - cron: "0 17 * * *"  # every day at 5pm UTC (10:30 PM IST)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Updated on $(date)" > daily.txt

      - name: Commit and push changes
        run: |
          git config user.name "Ajinkya Ghuge"
          git config user.email "ajinkyaghuge95@gmail.com"
          git add .
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git push
