name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a fake change
        run: |
          date > update.txt
          git config --global user.name 'Ajinkya Bot'
          git config --global user.email 'ajinkya@example.com'
          git add .
          git commit -m "Daily contribution 🌱"
          git push
